CREATE USER ${username} WITH PASSWORD ${password};
GRANT CONNECT ON DATABASE ${database} TO ${username};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema} GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO ${username};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema} GRANT USAGE ON SEQUENCES TO ${username};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema} GRANT EXECUTE ON FUNCTIONS TO ${username};
REVOKE ALL
    ON ALL TABLES IN SCHEMA ${schema}
    FROM ${schema};

GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA ${schema}
    TO ${username};


